//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Asa.Salt.Web.Services.Contracts.Data
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(LessonQuestionAttributeContract))]
    [KnownType(typeof(MemberLessonContract))]
    public class LessonQuestionResponseContract : IEntity 
    {
        [DataMember]
        public int LessonQuestionResponseId { get; set; }
        [DataMember]
        public int LessonQuestionAttributeId { get; set; }
        [DataMember]
        public string ResponseValue { get; set; }
        [DataMember]
        public int GroupingNumber { get; set; }
        [DataMember]
        public string CreatedBy { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public string ModifiedBy { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        [DataMember]
        public int MemberLessonId { get; set; }
    
        [DataMember]
        public virtual LessonQuestionAttributeContract LessonQuestionAttribute { get; set; }
        [DataMember]
        public virtual MemberLessonContract MemberLesson { get; set; }
    }
    
}
