//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Asa.Salt.Web.Services.Contracts.Data
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(LessonQuestionContract))]
    [KnownType(typeof(LessonQuestionResponseContract))]
    public class LessonQuestionAttributeContract : IEntity 
    {
        public LessonQuestionAttributeContract()
        {
            this.LessonQuestionResponses = new HashSet<LessonQuestionResponseContract>();
        }
    
        [DataMember]
        public int LessonQuestionAttributeId { get; set; }
        [DataMember]
        public int LessonQuestionId { get; set; }
        [DataMember]
        public string CreatedBy { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public string ModifiedBy { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        [DataMember]
        public string AttributeName { get; set; }
    
        [DataMember]
        public virtual LessonQuestionContract LessonQuestion { get; set; }
        [DataMember]
        public virtual ICollection<LessonQuestionResponseContract> LessonQuestionResponses { get; set; }
    }
    
}
