//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Asa.Salt.Web.Services.Contracts.Data
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(RefAnswerContract))]
    [KnownType(typeof(RefQuestionContract))]
    [KnownType(typeof(MemberContract))]
    public class MemberQuestionAnswerContract : IEntity 
    {
        [DataMember]
        public int MemberQuestionAnswerID { get; set; }
        [DataMember]
        public int MemberID { get; set; }
        [DataMember]
        public int RefQuestionID { get; set; }
        [DataMember]
        public int RefAnswerID { get; set; }
        [DataMember]
        public string CreatedBy { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public string ModifiedBy { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        [DataMember]
        public virtual MemberContract Member { get; set; }
        [DataMember]
        public virtual RefAnswerContract RefAnswer { get; set; }
        [DataMember]
        public virtual RefQuestionContract RefQuestion { get; set; }
        [DataMember]
        public string FreeformAnswerText { get; set; }
    }
    
}
