//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Asa.Salt.Web.Services.Contracts.Data
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(MemberContract))]
    [KnownType(typeof(AlertTypeContract))]
    public class MemberAlertContract : IEntity 
    {
        [DataMember]
        public int MemberAlertId { get; set; }
        [DataMember]
        public int MemberId { get; set; }
        [DataMember]
        public int AlertTypeId { get; set; }
        [DataMember]
        public string AlertTitle { get; set; }
        [DataMember]
        public string AlertLogoUrl { get; set; }
        [DataMember]
        public string AlertMessage { get; set; }
        [DataMember]
        public Nullable<System.DateTime> AlertIssueDate { get; set; }
        [DataMember]
        public bool IsAlertViewed { get; set; }
        [DataMember]
        public string AlertLink { get; set; }
        [DataMember]
        public string CreatedBy { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public string ModifiedBy { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [DataMember]
        public virtual MemberContract Member { get; set; }
        [DataMember]
        public virtual AlertTypeContract AlertType { get; set; }
    }
    
}
