//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Asa.Salt.Web.Services.Contracts.Data
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(MemberContract))]
    [KnownType(typeof(RefProfileAnswerContract))]
    public class MemberProfileAnswerContract : IEntity 
    {
        [DataMember]
        public int MemberProfileAnswerID { get; set; }
        [DataMember]
        public int MemberID { get; set; }
        [DataMember]
        public int RefProfileAnswerID { get; set; }
        [DataMember]
        public string CustomValue { get; set; }
        [DataMember]
        public string CreatedBy { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public string ModifiedBy { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [DataMember]
        public virtual MemberContract Member { get; set; }
        [DataMember]
        public virtual RefProfileAnswerContract RefProfileAnswer { get; set; }
    }
    
}
