//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Asa.Salt.Web.Common.Types.Enums;


namespace Asa.Salt.Web.Services.Contracts.Data
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(MemberContract))]
    [KnownType(typeof(RecordSourceContract))]
    public class MemberReportedLoanContract : IEntity 
    {
        [DataMember]
        public int MemberReportedLoanId { get; set; }
        [DataMember]
        public int MemberId { get; set; }
        [DataMember]
        public string LoanType { get; set; }
        [DataMember]
        public string LoanStatus { get; set; }
        [DataMember]
        public Nullable<decimal> PrincipalOutstandingAmount { get; set; }
        [DataMember]
        public Nullable<decimal> InterestRate { get; set; }
        [DataMember]
        public Nullable<int> ReceivedYear { get; set; }
        [DataMember]
        public Nullable<decimal> OriginalLoanAmount { get; set; }
        [DataMember]
        public Nullable<int> LoanTerm { get; set; }
        [DataMember]
        public int RecordSourceId { get; set; }
        [DataMember]
        public string CreatedBy { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public string ModifiedBy { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        [DataMember]
        public string LoanName { get; set; }
        [DataMember]
        public Nullable<System.DateTime> OriginalLoanDate { get; set; }
        [DataMember]
        public Nullable<decimal> MonthlyPaymentAmount { get; set; }
        [DataMember]
        public string ServicingOrganizationName { get; set; }
        [DataMember]
        public LoanInterestRateType InterestRateType { get; set; } 
    
        [DataMember]
        public virtual MemberContract Member { get; set; }
        [DataMember]
        public virtual RecordSourceContract RecordSource { get; set; }
    }
    
}
