//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Services.Contracts.Data
{
    [DataContract(IsReference = true)]
    public partial class RefEmailTemplateContract : IEntity 
    {
        [DataMember]
        public int RefEmailTemplateID { get; set; }
        [DataMember]
        public string EmailTemplateCode { get; set; }
        [DataMember]
        public string EmailTemplateTitle { get; set; }
        [DataMember]
        public string EmailSubject { get; set; }
        [DataMember]
        public string EmailBody { get; set; }
        [DataMember]
        public string EmailBodyText { get; set; }
        [DataMember]
        public Nullable<System.Guid> EmailTemplateExternalID { get; set; }
        [DataMember]
        public string CreatedBy { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public string ModifiedBy { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
    
}
