//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Asa.Salt.Web.Services.Contracts.Data
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(RefLessonLookupDataContract))]
    public class RefLessonLookupDataTypeContract : IEntity 
    {
        public RefLessonLookupDataTypeContract()
        {
            this.RefLessonLookupDatas = new HashSet<RefLessonLookupDataContract>();
        }
    
        [DataMember]
        public int RefLessonLookupDataTypeId { get; set; }
        [DataMember]
        public string Description { get; set; }
    
        [DataMember]
        public virtual ICollection<RefLessonLookupDataContract> RefLessonLookupDatas { get; set; }
    }
    
}
