//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Asa.Salt.Web.Services.Contracts.Data
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(MemberProductContract))]
    public class RefProductContract : IEntity 
    {
        public RefProductContract()
        {
            this.MemberProducts = new HashSet<MemberProductContract>();
            this.RefProductType = new RefProductTypeContract();
        }
    
        [DataMember]
        public int RefProductID { get; set; }
        [DataMember]
        public string ProductName { get; set; }
        [DataMember]
        public string ProductDescription { get; set; }
        [DataMember]
        public bool IsProductActive { get; set; }
        [DataMember]
        public string CreatedBy { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public string ModifiedBy { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        [DataMember]
        public int RefProductTypeID { get; set; }
    
        [DataMember]
        public virtual ICollection<MemberProductContract> MemberProducts { get; set; }
        [DataMember]
        public virtual RefProductTypeContract RefProductType { get; set; }
    }
    
}
