//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Asa.Salt.Web.Services.Contracts.Data
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(MemberProfileAnswerContract))]
    [KnownType(typeof(RefProfileQuestionContract))]
    public class RefProfileAnswerContract : IEntity 
    {
        public RefProfileAnswerContract()
        {
            this.MemberProfileAnswers = new HashSet<MemberProfileAnswerContract>();
        }
    
        [DataMember]
        public int RefProfileAnswerID { get; set; }
        [DataMember]
        public int RefProfileQuestionID { get; set; }
        [DataMember]
        public string ProfileAnswerName { get; set; }
        [DataMember]
        public string ProfileAnswerDescription { get; set; }
        [DataMember]
        public string CreatedBy { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public string ModifiedBy { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        [DataMember]
        public byte ProfileAnswerExternalID { get; set; }
        [DataMember]
        public bool IsProfileAnswerActive { get; set; }
        [DataMember]
        public Nullable<short> ProfileAnswerDisplayOrder { get; set; }
    
        [DataMember]
        public virtual ICollection<MemberProfileAnswerContract> MemberProfileAnswers { get; set; }
        [DataMember]
        public virtual RefProfileQuestionContract RefProfileQuestion { get; set; }
    }
    
}
