//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Asa.Salt.Web.Services.Contracts.Data
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(RefProfileAnswerContract))]
    [KnownType(typeof(RefProfileQuestionTypeContract))]
    public class RefProfileQuestionContract : IEntity 
    {
        public RefProfileQuestionContract()
        {
            this.RefProfileAnswers = new HashSet<RefProfileAnswerContract>();
        }
    
        [DataMember]
        public int RefProfileQuestionID { get; set; }
        [DataMember]
        public string ProfileQuestionName { get; set; }
        [DataMember]
        public string ProfileQuestionDescription { get; set; }
        [DataMember]
        public string CreatedBy { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public string ModifiedBy { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        [DataMember]
        public byte ProfileQuestionExternalID { get; set; }
        [DataMember]
        public Nullable<int> RefProfileQuestionTypeID { get; set; }
        [DataMember]
        public bool IsProfileQuestionActive { get; set; }
        [DataMember]
        public Nullable<short> ProfileQuestionPriority { get; set; }
        [DataMember]
        public bool IsInLineProfileQuestion { get; set; }
    
        [DataMember]
        public virtual ICollection<RefProfileAnswerContract> RefProfileAnswers { get; set; }
        [DataMember]
        public virtual RefProfileQuestionTypeContract RefProfileQuestionType { get; set; }
    }
    
}
