//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Asa.Salt.Web.Services.Contracts.Data
{
    [DataContract(IsReference = true)]
    public class RefSourceQuestionAnswerContract : IEntity 
    {
        [DataMember]
        public int RefSourceQuestionAnswerID { get; set; }
        [DataMember]
        public int RefSourceQuestionID { get; set; }
        [DataMember]
        public int RefAnswerID { get; set; }
        [DataMember]
        public string AnswerText { get; set; }
        [DataMember]
        public Nullable<int> ExternalSourceQuestionAnswerID { get; set; }
        [DataMember]
        public byte AnswerDisplayOrder { get; set; }
        [DataMember]
        public bool IsRefSourceQuestionAnswerActive { get; set; }
        [DataMember]
        public string CreatedBy { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public string ModifiedBy { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        [DataMember]
        public virtual RefAnswerContract RefAnswer { get; set; }
        [DataMember]
        public virtual RefSourceQuestionContract RefSourceQuestion { get; set; }
    }
    
}
