//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Asa.Salt.Web.Services.Contracts.Data
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(RefStateContract))]
    [KnownType(typeof(RefSalaryEstimatorSchoolMajorContract))]
    public class RefSalaryEstimatorSchoolContract : IEntity 
    {
        public RefSalaryEstimatorSchoolContract()
        {
            this.RefSalaryEstimatorSchoolMajors = new HashSet<RefSalaryEstimatorSchoolMajorContract>();
        }
    
        [DataMember]
        public int RefSalaryEstimatorSchoolID { get; set; }
        [DataMember]
        public int SourceSchoolID { get; set; }
        [DataMember]
        public int RefStateID { get; set; }
        [DataMember]
        public string SchoolName { get; set; }
        [DataMember]
        public decimal WageFactorStart { get; set; }
        [DataMember]
        public decimal WageFactorMid { get; set; }
        [DataMember]
        public byte WageFactorTier { get; set; }
        [DataMember]
        public string DataSource { get; set; }
        [DataMember]
        public string CreatedBy { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public string ModifiedBy { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [DataMember]
        public virtual RefStateContract RefState { get; set; }
        [DataMember]
        public virtual ICollection<RefSalaryEstimatorSchoolMajorContract> RefSalaryEstimatorSchoolMajors { get; set; }
    }
    
}
