//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Asa.Salt.Web.Services.Contracts.Data
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(RefUserProfileContract))]
    [KnownType(typeof(RefUserProfileItemContract))]
    [KnownType(typeof(UserProfileDetailContract))]
    public partial class RefUserProfileUserProfileItemContract : IEntity 
    {
        public RefUserProfileUserProfileItemContract()
        {
            this.UserProfileDetails = new HashSet<UserProfileDetailContract>();
        }
    
        [DataMember]
        public int RefUserProfileUserProfileItemID { get; set; }
        [DataMember]
        public int RefUserProfileID { get; set; }
        [DataMember]
        public int RefUserProfileItemID { get; set; }
        [DataMember]
        public string CreatedBy { get; set; }
        [DataMember]
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [DataMember]
        public virtual RefUserProfileContract RefUserProfile { get; set; }
        [DataMember]
        public virtual RefUserProfileItemContract RefUserProfileItem { get; set; }
        [DataMember]
        public virtual ICollection<UserProfileDetailContract> UserProfileDetails { get; set; }
    }
    
}
