//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Asa.Salt.Web.Services.Contracts.Data
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(SurveyContract))]
    [KnownType(typeof(SurveyResponseContract))]
    public class SurveyOptionContract : IEntity 
    {
        public SurveyOptionContract()
        {
            this.SurveyResponses = new HashSet<SurveyResponseContract>();
        }
    
        [DataMember]
        public int SurveyOptionId { get; set; }
        [DataMember]
        public int SurveyId { get; set; }
        [DataMember]
        public string OptionValue { get; set; }
        [DataMember]
        public string CreatedBy { get; set; }
        [DataMember]
        public int OrderNumber { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public string ModifiedBy { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        /// <summary>
        /// Gets or sets the total response count.
        /// </summary>
        /// <value>
        /// The total response count.
        /// </value>
        [DataMember]
        public int TotalResponseCount { get; set; }
    
        [DataMember]
        public virtual SurveyContract Survey { get; set; }
        [DataMember]
        public virtual ICollection<SurveyResponseContract> SurveyResponses { get; set; }
    }
    
}
