//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Asa.Salt.Web.Services.Contracts.Data
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(VLCUserResponseContract))]
    public class VLCQuestionContract : IEntity 
    {
        public VLCQuestionContract()
        {
            this.VLCUserResponses = new HashSet<VLCUserResponseContract>();
        }
    
        [DataMember]
        public int VLCQuestionID { get; set; }
        [DataMember]
        public string CreatedBy { get; set; }
        [DataMember]
        public System.DateTime CreatedDate { get; set; }
        [DataMember]
        public short ExternalItemID { get; set; }
        [DataMember]
        public byte ExternalItemVersionNumber { get; set; }
        [DataMember]
        public string Question { get; set; }
    
        [DataMember]
        public virtual ICollection<VLCUserResponseContract> VLCUserResponses { get; set; }
    }
    
}
