//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace Asa.Salt.Web.Services.Contracts.Data
{
    [DataContract(IsReference = true)]
    public class vMemberAlertsContract : IEntity 
    {
        [DataMember]
        public int MemberID { get; set; }
        [DataMember]
        public string FirstName { get; set; }
        [DataMember]
        public string LastName { get; set; }
        [DataMember]
        public string EmailAddress { get; set; }
        [DataMember]
        public bool IsContactAllowed { get; set; }
        [DataMember]
        public Nullable<int> RefSchoolID { get; set; }
        [DataMember]
        public string AlertTitle { get; set; }
        [DataMember]
        public string AlertLogoURL { get; set; }
        [DataMember]
        public string AlertMessage { get; set; }
        [DataMember]
        public Nullable<System.DateTime> AlertIssueDate { get; set; }
        [DataMember]
        public bool IsAlertViewed { get; set; }
        [DataMember]
        public string AlertLink { get; set; }
        [DataMember]
        public string AlertTypeName { get; set; }
        [DataMember]
        public int RefAlertTypeID { get; set; }
    }
    
}
