//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASA.Web.Services.AddrValidationService.Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASA.Web.Services.AddrValidationService.Validation.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressLine1 is too long.
        /// </summary>
        public static string error_addressline1_length_invalid {
            get {
                return ResourceManager.GetString("error_addressline1_length_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string error_addressline1_required {
            get {
                return ResourceManager.GetString("error_addressline1_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressLine2 is too long.
        /// </summary>
        public static string error_addressline2_length_invalid {
            get {
                return ResourceManager.GetString("error_addressline2_length_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is too long.
        /// </summary>
        public static string error_city_length_invalid {
            get {
                return ResourceManager.GetString("error_city_length_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string error_city_required {
            get {
                return ResourceManager.GetString("error_city_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string error_country_required {
            get {
                return ResourceManager.GetString("error_country_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string error_emailaddress_invalid {
            get {
                return ResourceManager.GetString("error_emailaddress_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string error_emailaddress_required {
            get {
                return ResourceManager.GetString("error_emailaddress_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string error_firstname_invalid {
            get {
                return ResourceManager.GetString("error_firstname_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is too long.
        /// </summary>
        public static string error_firstname_length_invalid {
            get {
                return ResourceManager.GetString("error_firstname_length_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string error_firstname_required {
            get {
                return ResourceManager.GetString("error_firstname_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string error_lastname_invalid {
            get {
                return ResourceManager.GetString("error_lastname_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is too long.
        /// </summary>
        public static string error_lastname_length_invalid {
            get {
                return ResourceManager.GetString("error_lastname_length_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string error_lastname_required {
            get {
                return ResourceManager.GetString("error_lastname_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string error_middleinitial_invalid {
            get {
                return ResourceManager.GetString("error_middleinitial_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MI is too long.
        /// </summary>
        public static string error_middleinitial_length_invalid {
            get {
                return ResourceManager.GetString("error_middleinitial_length_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.  Please enter only numbers..
        /// </summary>
        public static string error_phonenumber_invalid {
            get {
                return ResourceManager.GetString("error_phonenumber_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string error_phonenumber_required {
            get {
                return ResourceManager.GetString("error_phonenumber_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string error_ssn_invalid {
            get {
                return ResourceManager.GetString("error_ssn_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string error_ssn_required {
            get {
                return ResourceManager.GetString("error_ssn_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string error_stateid_required {
            get {
                return ResourceManager.GetString("error_stateid_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string error_zip_invalid {
            get {
                return ResourceManager.GetString("error_zip_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip length is too long.
        /// </summary>
        public static string error_zip_length_invalid {
            get {
                return ResourceManager.GetString("error_zip_length_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string error_zip_required {
            get {
                return ResourceManager.GetString("error_zip_required", resourceCulture);
            }
        }
    }
}
