//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
     public abstract class DomainObject<TKeyType> : IDomainObject<TKeyType>
        {
            public abstract TKeyType Id { get;  }
    
    		public virtual IList<ValidationResult> Validate()
    		{
    			return new List<ValidationResult>();
    		}
        }
    
        public interface IDomainObject<TKeyType>
        {
            TKeyType Id { get; }
    
    		IList<ValidationResult> Validate();
        }
}
