//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class LessonQuestion : DomainObject<int> 
    {
        public LessonQuestion()
        {
            this.LessonQuestionAttributes = new HashSet<LessonQuestionAttribute>();
        }
    
        public int LessonQuestionId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int LessonStepId { get; set; }
        public string Question { get; set; }
        public int OrderNumber { get; set; }
        public bool HasMultipleValues { get; set; }
    
        public virtual ICollection<LessonQuestionAttribute> LessonQuestionAttributes { get; set; }
        public virtual LessonStep LessonStep { get; set; }
    }
    
}
