//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class LessonStep : DomainObject<int> 
    {
        public LessonStep()
        {
            this.LessonQuestions = new HashSet<LessonQuestion>();
        }
    
        public int LessonStepId { get; set; }
        public int LessonId { get; set; }
        public string LessonStepName { get; set; }
        public int OrderNumber { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual ICollection<LessonQuestion> LessonQuestions { get; set; }
    }
    
}
