//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class MemberReportedLoan : DomainObject<int> 
    {
        public int MemberReportedLoanId { get; set; }
        public int MemberId { get; set; }
        public string LoanType { get; set; }
        public string LoanStatus { get; set; }
        public Nullable<decimal> PrincipalOutstandingAmount { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<int> ReceivedYear { get; set; }
        public Nullable<decimal> OriginalLoanAmount { get; set; }
        public Nullable<int> LoanTerm { get; set; }
        public int RecordSourceId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string LoanName { get; set; }
        public Nullable<System.DateTime> OriginalLoanDate { get; set; }
        public Nullable<decimal> MonthlyPaymentAmount { get; set; }
        public string ServicingOrganizationName { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual RecordSource RecordSource { get; set; }
    }
    
}
