//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class MemberContentInteraction : DomainObject<int> 
    {
        public int MemberContentInteractionID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string ContentID { get; set; }
        public int RefContentInteractionTypeID { get; set; }
        public string MemberContentInteractionValue { get; set; }
        public System.DateTime InteractionDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string MemberContentComment { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual RefContentInteractionType RefContentInteractionType { get; set; }
    }
    
}
