//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class MemberLesson : DomainObject<int> 
    {
        public MemberLesson()
        {
            this.LessonQuestionResponses = new HashSet<LessonQuestionResponse>();
        }
    
        public int MemberLessonId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public int LessonId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CurrentStep { get; set; }
        public int LessonUserId { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual Member Member { get; set; }
        public virtual ICollection<LessonQuestionResponse> LessonQuestionResponses { get; set; }
    }
    
}
