//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class OrganizationToDoList : DomainObject<int> 
    {
        public int OrganizationToDoListID { get; set; }
        public int RefOrganizationID { get; set; }
        public int RefToDoTypeID { get; set; }
        public int RefToDoStatusID { get; set; }
        public string ContentID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Headline { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual RefToDoStatus RefToDoStatus { get; set; }
        public virtual RefToDoType RefToDoType { get; set; }
        public virtual RefOrganization RefOrganization { get; set; }
    }
    
}
