//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class RecordSource : DomainObject<int> 
    {
        public RecordSource()
        {
            this.MemberReportedLoans = new HashSet<MemberReportedLoan>();
        }
    
        public int RecordSourceId { get; set; }
        public string RecordSourceName { get; set; }
        public string RecordSourceDescription { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<MemberReportedLoan> MemberReportedLoans { get; set; }
    }
    
}
