//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class RefGeographicIndex : DomainObject<int> 
    {
        public int RefGeographicIndexID { get; set; }
        public int RefStateID { get; set; }
        public decimal CityCode { get; set; }
        public string MetroName { get; set; }
        public string UrbanAreaName { get; set; }
        public decimal CompositeIndex { get; set; }
        public decimal GroceryIndex { get; set; }
        public decimal HousingIndex { get; set; }
        public decimal UtilitiesIndex { get; set; }
        public decimal TransportationIndex { get; set; }
        public decimal HealthIndex { get; set; }
        public decimal MiscellaneousIndex { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual RefState RefState { get; set; }
    }
    
}
