//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class RefLessonLookupData : DomainObject<int> 
    {
        public int RefLessonLookupDataId { get; set; }
        public int RefLessonLookupDataTypeId { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public string Value { get; set; }
    
        public virtual RefLessonLookupDataType RefLessonLookupDataType { get; set; }
    }
    
}
