//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class RefProfileAnswer : DomainObject<int> 
    {
        public RefProfileAnswer()
        {
            this.MemberProfileAnswers = new HashSet<MemberProfileAnswer>();
        }
    
        public int RefProfileAnswerID { get; set; }
        public int RefProfileQuestionID { get; set; }
        public string ProfileAnswerName { get; set; }
        public string ProfileAnswerDescription { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public byte ProfileAnswerExternalID { get; set; }
        public bool IsProfileAnswerActive { get; set; }
        public Nullable<short> ProfileAnswerDisplayOrder { get; set; }
    
        public virtual ICollection<MemberProfileAnswer> MemberProfileAnswers { get; set; }
        public virtual RefProfileQuestion RefProfileQuestion { get; set; }
    }
    
}
