//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class RefProduct : DomainObject<int> 
    {
        public RefProduct()
        {
            this.MemberProducts = new HashSet<MemberProduct>();
            this.RefOrganizationProducts = new HashSet<RefOrganizationProduct>();
        }
    
        public int RefProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public bool IsProductActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int RefProductTypeID { get; set; }
    
        public virtual ICollection<MemberProduct> MemberProducts { get; set; }
        public virtual ICollection<RefOrganizationProduct> RefOrganizationProducts { get; set; }
        public virtual RefProductType RefProductType { get; set; }
    }
    
}
