//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class RefRegistrationSource : DomainObject<int> 
    {
        public RefRegistrationSource()
        {
            this.Members = new HashSet<Member>();
        }
    
        public int RefRegistrationSourceId { get; set; }
        public string RegistrationSourceName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> RefRegistrationSourceTypeID { get; set; }
        public string RegistrationDetail { get; set; }
        public Nullable<int> RefCampaignID { get; set; }
        public Nullable<int> RefChannelID { get; set; }
    
        public virtual ICollection<Member> Members { get; set; }
        public virtual RefRegistrationSourceType RefRegistrationSourceType { get; set; }
        public virtual RefCampaign RefCampaign { get; set; }
        public virtual RefChannel RefChannel { get; set; }
    }
    
}
