//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class RefState : DomainObject<int> 
    {
        public RefState()
        {
            this.RefSalaryEstimatorSchools = new HashSet<RefSalaryEstimatorSchool>();
            this.RefGeographicIndexes = new HashSet<RefGeographicIndex>();
            this.RefOrganizations = new HashSet<RefOrganization>();
        }
    
        public int RefStateID { get; set; }
        public string StateCode { get; set; }
        public string StateName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ICollection<RefSalaryEstimatorSchool> RefSalaryEstimatorSchools { get; set; }
        public virtual ICollection<RefGeographicIndex> RefGeographicIndexes { get; set; }
        public virtual ICollection<RefOrganization> RefOrganizations { get; set; }
    }
    
}
