//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class RefSourceQuestion : DomainObject<int> 
    {
        public RefSourceQuestion()
        {
            this.RefSourceQuestionAnswers = new HashSet<RefSourceQuestionAnswer>();
        }
    
        public int RefSourceQuestionID { get; set; }
        public int RefSourceID { get; set; }
        public int RefQuestionID { get; set; }
        public Nullable<int> ExternalSourceQuestionID { get; set; }
        public string QuestionText { get; set; }
        public string SourceQuestionDescription { get; set; }
        public Nullable<byte> QuestionDisplayOrder { get; set; }
        public bool IsRefSourceQuestionActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual RefQuestion RefQuestion { get; set; }
        public virtual RefSource RefSource { get; set; }
        public virtual ICollection<RefSourceQuestionAnswer> RefSourceQuestionAnswers { get; set; }
    }
    
}
