//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class RefSourceQuestionAnswer : DomainObject<int> 
    {
        public int RefSourceQuestionAnswerID { get; set; }
        public int RefSourceQuestionID { get; set; }
        public int RefAnswerID { get; set; }
        public string AnswerText { get; set; }
        public Nullable<int> ExternalSourceQuestionAnswerID { get; set; }
        public Nullable<byte> AnswerDisplayOrder { get; set; }
        public bool IsRefSourceQuestionAnswerActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> RefDataTypeID { get; set; }
    
        public virtual RefAnswer RefAnswer { get; set; }
        public virtual RefSourceQuestion RefSourceQuestion { get; set; }
    }
    
}
