//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class RefSalaryEstimatorSchool : DomainObject<int> 
    {
        public RefSalaryEstimatorSchool()
        {
            this.RefSalaryEstimatorSchoolMajors = new HashSet<RefSalaryEstimatorSchoolMajor>();
        }
    
        public int RefSalaryEstimatorSchoolID { get; set; }
        public int SourceSchoolID { get; set; }
        public int RefStateID { get; set; }
        public string SchoolName { get; set; }
        public decimal WageFactorStart { get; set; }
        public decimal WageFactorMid { get; set; }
        public byte WageFactorTier { get; set; }
        public string DataSource { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual RefState RefState { get; set; }
        public virtual ICollection<RefSalaryEstimatorSchoolMajor> RefSalaryEstimatorSchoolMajors { get; set; }
    }
    
}
