//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class Survey : DomainObject<int> 
    {
        public Survey()
        {
            this.SurveyOptions = new HashSet<SurveyOption>();
        }
    
        public int SurveyId { get; set; }
        public string SurveyName { get; set; }
        public System.DateTime SurveyStartDate { get; set; }
        public Nullable<System.DateTime> SurveyEndDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string SurveyQuestion { get; set; }
        public string SurveyDescription { get; set; }
        public string SurveyPurpose { get; set; }
        public string ListOfValues { get; set; }
    
        public virtual ICollection<SurveyOption> SurveyOptions { get; set; }
    }
    
}
