//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class SurveyOption : DomainObject<int> 
    {
        public SurveyOption()
        {
            this.SurveyResponses = new HashSet<SurveyResponse>();
        }
    
        public int SurveyOptionId { get; set; }
        public int SurveyId { get; set; }
        public string OptionValue { get; set; }
        public string CreatedBy { get; set; }
        public int OrderNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Survey Survey { get; set; }
        public virtual ICollection<SurveyResponse> SurveyResponses { get; set; }
    }
    
}
