//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class VLCQuestion : DomainObject<int> 
    {
        public VLCQuestion()
        {
            this.VLCUserResponses = new HashSet<VLCUserResponse>();
        }
    
        public int VLCQuestionID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public short ExternalItemID { get; set; }
        public byte ExternalItemVersionNumber { get; set; }
        public string Question { get; set; }
    
        public virtual ICollection<VLCUserResponse> VLCUserResponses { get; set; }
    }
    
}
