//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class VLCUserProfile : DomainObject<int> 
    {
        public int MemberID { get; set; }
        public Nullable<System.DateTime> GraduationDate { get; set; }
        public string RepaymentStatus { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string EnrollmentStatus { get; set; }
        public int VLCUserProfileID { get; set; }
        public Nullable<int> AdjustedGrossIncome { get; set; }
        public Nullable<byte> FamilySize { get; set; }
        public string StateOfResidence { get; set; }
        public string TaxFilingStatus { get; set; }
    
        public virtual Member Member { get; set; }
    }
    
}
