//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class VLCUserResponse : DomainObject<int> 
    {
        public int VLCUserResponseID { get; set; }
        public int MemberID { get; set; }
        public int VLCQuestionID { get; set; }
        public string Response { get; set; }
        public System.DateTime ResponseDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual VLCQuestion VLCQuestion { get; set; }
    }
    
}
