//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class vMemberToDoList : DomainObject<int> 
    {
        public int MemberID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string ContentID { get; set; }
        public System.DateTime ToDoItemCreatedDate { get; set; }
        public string ToDoItemCreatedBy { get; set; }
        public Nullable<System.DateTime> ToDoItemModifiedDate { get; set; }
        public string ToDoItemModifiedBy { get; set; }
        public string ToDoTypeName { get; set; }
        public string ToDoStatusName { get; set; }
    }
    
}
