//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class vMemberAlerts : DomainObject<int> 
    {
        public int MemberID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public bool IsContactAllowed { get; set; }
        public string AlertTitle { get; set; }
        public string AlertLogoURL { get; set; }
        public string AlertMessage { get; set; }
        public Nullable<System.DateTime> AlertIssueDate { get; set; }
        public bool IsAlertViewed { get; set; }
        public string AlertLink { get; set; }
        public string AlertTypeName { get; set; }
        public int RefAlertTypeID { get; set; }
    }
    
}
