//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class vMemberQuestionAnswer : DomainObject<int> 
    {
        public int MemberID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> ExternalSourceQuestionAnswerID { get; set; }
        public Nullable<int> ExternalSourceQuestionID { get; set; }
        public string AnswerText { get; set; }
        public string StandardAnswerText { get; set; }
        public string QuestionText { get; set; }
        public string StandardQuestionText { get; set; }
        public int MemberQuestionAnswerID { get; set; }
        public int RefAnswerID { get; set; }
        public int RefQuestionID { get; set; }
        public int RefSourceID { get; set; }
        public string SourceName { get; set; }
        public string SourceDescription { get; set; }
        public int RefSourceQuestionID { get; set; }
        public string SourceQuestionDescription { get; set; }
        public Nullable<byte> AnswerDisplayOrder { get; set; }
        public Nullable<byte> QuestionDisplayOrder { get; set; }
        public int RefQuestions_refQuestionID { get; set; }
        public int RefAnswer_refAnswerID { get; set; }
        public int RefSourceQuestionAnswer_refAnswerID { get; set; }
        public int RefSourceQuestionAnswerID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string FreeformAnswerText { get; set; }
    }
    
}
