//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class vMemberAcademicInfo : DomainObject<int> 
    {
        public int MemberID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime MemberFirstActivationDate { get; set; }
        public Nullable<int> MemberOrganizationID { get; set; }
        public Nullable<System.DateTime> EffectiveStartDate { get; set; }
        public Nullable<System.DateTime> EffectiveEndDate { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationDescription { get; set; }
        public string OrganizationExternalID { get; set; }
        public Nullable<bool> IsContracted { get; set; }
        public string OPECode { get; set; }
        public string BranchCode { get; set; }
        public string OrganizationLogoName { get; set; }
        public Nullable<int> MemberActivationHistoryID { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<System.DateTime> DeactivationDate { get; set; }
        public bool IsContactAllowed { get; set; }
        public Nullable<int> RefOrganizationID { get; set; }
        public int RefRegistrationSourceID { get; set; }
        public Nullable<System.Guid> InvitationToken { get; set; }
        public System.Guid ActiveDirectoryKey { get; set; }
        public string DisplayName { get; set; }
        public bool IsMemberActive { get; set; }
        public string EnrollmentStatusDescription { get; set; }
        public string EnrollmentStatusCode { get; set; }
        public Nullable<int> RefEnrollmentStatusID { get; set; }
        public Nullable<int> RefGradeLevelID { get; set; }
        public string GradeLevelCode { get; set; }
        public string GradeLevelDescription { get; set; }
        public bool WelcomeEmailSent { get; set; }
    }
    
}
