//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Asa.Salt.Web.Services.Domain
{
    public partial class vSourceQuestion : DomainObject<int> 
    {
        public int StandardQuestion_refQuestionID { get; set; }
        public string StandardQuestionText { get; set; }
        public string SourceName { get; set; }
        public string SourceDescription { get; set; }
        public int RefSourceID { get; set; }
        public int RefSourceQuestionID { get; set; }
        public string QuestionText { get; set; }
        public string SourceQuestionDescription { get; set; }
        public Nullable<int> ExternalSourceQuestionID { get; set; }
        public byte QuestionDisplayOrder { get; set; }
        public Nullable<int> MemberQuestionAnswerID { get; set; }
        public Nullable<int> RefAnswerID { get; set; }
        public Nullable<int> MemberID { get; set; }
    }
    
}
