//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASA.Web.Services.AlertService.Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASA.Web.Services.AlertService.Validation.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance at Start of Deferment is invalid.
        /// </summary>
        public static string error_balanceatstartdeferment_invalid {
            get {
                return ResourceManager.GetString("error_balanceatstartdeferment_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbearance Payment Amount is invalid.
        /// </summary>
        public static string error_forbearancepaymentamount_invalid {
            get {
                return ResourceManager.GetString("error_forbearancepaymentamount_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Rate is invalid.
        /// </summary>
        public static string error_interestrate_invalid {
            get {
                return ResourceManager.GetString("error_interestrate_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montly Income is invalid.
        /// </summary>
        public static string error_montlyincome_invalid {
            get {
                return ResourceManager.GetString("error_montlyincome_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Forbearance Payments is invalid.
        /// </summary>
        public static string error_numberofforbearancepayments_invalid {
            get {
                return ResourceManager.GetString("error_numberofforbearancepayments_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Months in Deferment is invalid.
        /// </summary>
        public static string error_numberofmonthsindeferment_invalid {
            get {
                return ResourceManager.GetString("error_numberofmonthsindeferment_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Months in Forbearance is invalid.
        /// </summary>
        public static string error_numberofmonthsinforbearance_invalid {
            get {
                return ResourceManager.GetString("error_numberofmonthsinforbearance_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Payments is invalid.
        /// </summary>
        public static string error_numberofpayments_invalid {
            get {
                return ResourceManager.GetString("error_numberofpayments_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal Amount is invalid.
        /// </summary>
        public static string error_principalamount_invalid {
            get {
                return ResourceManager.GetString("error_principalamount_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlertType is invalid.
        /// </summary>
        public static string error_SelfReportedtype_invalid {
            get {
                return ResourceManager.GetString("error_Alerttype_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlertType value is invalid.
        /// </summary>
        public static string error_SelfReportedtype_value_invalid {
            get {
                return ResourceManager.GetString("error_Alerttype_value_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Rate is required.
        /// </summary>
        public static string error_src_interestrate_required {
            get {
                return ResourceManager.GetString("error_src_interestrate_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Rate must be greater than 0.
        /// </summary>
        public static string error_src_interestrate_value_invalid {
            get {
                return ResourceManager.GetString("error_src_interestrate_value_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Payments is required.
        /// </summary>
        public static string error_src_numberofpayments_required {
            get {
                return ResourceManager.GetString("error_src_numberofpayments_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Payments must be greater than 0.
        /// </summary>
        public static string error_src_numberofpayments_value_invalid {
            get {
                return ResourceManager.GetString("error_src_numberofpayments_value_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal Amount is required.
        /// </summary>
        public static string error_src_principalamount_required {
            get {
                return ResourceManager.GetString("error_src_principalamount_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal Amount must be greater than 0.
        /// </summary>
        public static string error_src_principalamount_value_invalid {
            get {
                return ResourceManager.GetString("error_src_principalamount_value_invalid", resourceCulture);
            }
        }
    }
}
