//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASA.Web.Utility.ActiveDirectory.Configuration
{
    
    
    /// <summary>
    /// The ActiveDirectoryConnectorSection Configuration Section.
    /// </summary>
    public partial class ActiveDirectoryConnectorSection : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the ActiveDirectoryConnectorSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string ActiveDirectoryConnectorSectionSectionName = "activeDirectoryConnectorSection";
        
        /// <summary>
        /// Gets the ActiveDirectoryConnectorSection instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public static global::ASA.Web.Utility.ActiveDirectory.Configuration.ActiveDirectoryConnectorSection Instance
        {
            get
            {
                return ((global::ASA.Web.Utility.ActiveDirectory.Configuration.ActiveDirectoryConnectorSection)(global::System.Configuration.ConfigurationManager.GetSection(global::ASA.Web.Utility.ActiveDirectory.Configuration.ActiveDirectoryConnectorSection.ActiveDirectoryConnectorSectionSectionName)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ASA.Web.Utility.ActiveDirectory.Configuration.ActiveDirectoryConnectorSection.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::ASA.Web.Utility.ActiveDirectory.Configuration.ActiveDirectoryConnectorSection.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region UserID Property
        /// <summary>
        /// The XML name of the <see cref="UserID"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string UserIDPropertyName = "userID";
        
        /// <summary>
        /// Gets or sets the UserID.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The UserID.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ASA.Web.Utility.ActiveDirectory.Configuration.ActiveDirectoryConnectorSection.UserIDPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public global::ASA.Web.Utility.ActiveDirectory.Configuration.UserID UserID
        {
            get
            {
                return ((global::ASA.Web.Utility.ActiveDirectory.Configuration.UserID)(base[global::ASA.Web.Utility.ActiveDirectory.Configuration.ActiveDirectoryConnectorSection.UserIDPropertyName]));
            }
            set
            {
                base[global::ASA.Web.Utility.ActiveDirectory.Configuration.ActiveDirectoryConnectorSection.UserIDPropertyName] = value;
            }
        }
        #endregion
        
        #region Password Property
        /// <summary>
        /// The XML name of the <see cref="Password"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string PasswordPropertyName = "password";
        
        /// <summary>
        /// Gets or sets the Password.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Password.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ASA.Web.Utility.ActiveDirectory.Configuration.ActiveDirectoryConnectorSection.PasswordPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public global::ASA.Web.Utility.ActiveDirectory.Configuration.Password Password
        {
            get
            {
                return ((global::ASA.Web.Utility.ActiveDirectory.Configuration.Password)(base[global::ASA.Web.Utility.ActiveDirectory.Configuration.ActiveDirectoryConnectorSection.PasswordPropertyName]));
            }
            set
            {
                base[global::ASA.Web.Utility.ActiveDirectory.Configuration.ActiveDirectoryConnectorSection.PasswordPropertyName] = value;
            }
        }
        #endregion
        
        #region UserContainer Property
        /// <summary>
        /// The XML name of the <see cref="UserContainer"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string UserContainerPropertyName = "userContainer";
        
        /// <summary>
        /// Gets or sets the UserContainer.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The UserContainer.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ASA.Web.Utility.ActiveDirectory.Configuration.ActiveDirectoryConnectorSection.UserContainerPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public global::ASA.Web.Utility.ActiveDirectory.Configuration.UserContainer UserContainer
        {
            get
            {
                return ((global::ASA.Web.Utility.ActiveDirectory.Configuration.UserContainer)(base[global::ASA.Web.Utility.ActiveDirectory.Configuration.ActiveDirectoryConnectorSection.UserContainerPropertyName]));
            }
            set
            {
                base[global::ASA.Web.Utility.ActiveDirectory.Configuration.ActiveDirectoryConnectorSection.UserContainerPropertyName] = value;
            }
        }
        #endregion
        
        #region Domain Property
        /// <summary>
        /// The XML name of the <see cref="Domain"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string DomainPropertyName = "domain";
        
        /// <summary>
        /// Gets or sets the Domain.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Domain.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ASA.Web.Utility.ActiveDirectory.Configuration.ActiveDirectoryConnectorSection.DomainPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public global::ASA.Web.Utility.ActiveDirectory.Configuration.Domain Domain
        {
            get
            {
                return ((global::ASA.Web.Utility.ActiveDirectory.Configuration.Domain)(base[global::ASA.Web.Utility.ActiveDirectory.Configuration.ActiveDirectoryConnectorSection.DomainPropertyName]));
            }
            set
            {
                base[global::ASA.Web.Utility.ActiveDirectory.Configuration.ActiveDirectoryConnectorSection.DomainPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace ASA.Web.Utility.ActiveDirectory.Configuration
{
    
    
    /// <summary>
    /// The UserContainer Configuration Element.
    /// </summary>
    public partial class UserContainer : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Value Property
        /// <summary>
        /// The XML name of the <see cref="Value"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string ValuePropertyName = "value";
        
        /// <summary>
        /// Gets or sets the Value.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Value.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ASA.Web.Utility.ActiveDirectory.Configuration.UserContainer.ValuePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Value
        {
            get
            {
                return ((string)(base[global::ASA.Web.Utility.ActiveDirectory.Configuration.UserContainer.ValuePropertyName]));
            }
            set
            {
                base[global::ASA.Web.Utility.ActiveDirectory.Configuration.UserContainer.ValuePropertyName] = value;
            }
        }
        #endregion
    }
}
namespace ASA.Web.Utility.ActiveDirectory.Configuration
{
    
    
    /// <summary>
    /// The UserID Configuration Element.
    /// </summary>
    public partial class UserID : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Value Property
        /// <summary>
        /// The XML name of the <see cref="Value"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string ValuePropertyName = "value";
        
        /// <summary>
        /// Gets or sets the Value.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Value.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ASA.Web.Utility.ActiveDirectory.Configuration.UserID.ValuePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Value
        {
            get
            {
                return ((string)(base[global::ASA.Web.Utility.ActiveDirectory.Configuration.UserID.ValuePropertyName]));
            }
            set
            {
                base[global::ASA.Web.Utility.ActiveDirectory.Configuration.UserID.ValuePropertyName] = value;
            }
        }
        #endregion
    }
}
namespace ASA.Web.Utility.ActiveDirectory.Configuration
{
    
    
    /// <summary>
    /// The Password Configuration Element.
    /// </summary>
    public partial class Password : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Value Property
        /// <summary>
        /// The XML name of the <see cref="Value"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string ValuePropertyName = "value";
        
        /// <summary>
        /// Gets or sets the Value.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Value.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ASA.Web.Utility.ActiveDirectory.Configuration.Password.ValuePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Value
        {
            get
            {
                return ((string)(base[global::ASA.Web.Utility.ActiveDirectory.Configuration.Password.ValuePropertyName]));
            }
            set
            {
                base[global::ASA.Web.Utility.ActiveDirectory.Configuration.Password.ValuePropertyName] = value;
            }
        }
        #endregion
    }
}
namespace ASA.Web.Utility.ActiveDirectory.Configuration
{
    
    
    /// <summary>
    /// The Domain Configuration Element.
    /// </summary>
    public partial class Domain : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Value Property
        /// <summary>
        /// The XML name of the <see cref="Value"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        internal const string ValuePropertyName = "value";
        
        /// <summary>
        /// Gets or sets the Value.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.0.0")]
        [global::System.ComponentModel.DescriptionAttribute("The Value.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ASA.Web.Utility.ActiveDirectory.Configuration.Domain.ValuePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Value
        {
            get
            {
                return ((string)(base[global::ASA.Web.Utility.ActiveDirectory.Configuration.Domain.ValuePropertyName]));
            }
            set
            {
                base[global::ASA.Web.Utility.ActiveDirectory.Configuration.Domain.ValuePropertyName] = value;
            }
        }
        #endregion
    }
}
