//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASA.Web.Services.AppToolService.Proxy.AppTool {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppToolServiceCriteriaType", Namespace="http://asa.org/contracts/apptoolServiceCriteria")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ASA.Web.Services.AppToolService.Proxy.AppTool.CriteriaAppTool_PersonAppToolType))]
    public partial class AppToolServiceCriteriaType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxEntitiesField;
        
        private ASA.Web.Services.AppToolService.Proxy.AppTool.LogicalOperatorType LogicalOperatorField;
        
        private ASA.Web.Services.AppToolService.Proxy.AppTool.ReturnListType ListReturnTypesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASA.Web.Services.AppToolService.Proxy.AppTool.SortFields SortFieldsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxEntities {
            get {
                return this.MaxEntitiesField;
            }
            set {
                if ((this.MaxEntitiesField.Equals(value) != true)) {
                    this.MaxEntitiesField = value;
                    this.RaisePropertyChanged("MaxEntities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.LogicalOperatorType LogicalOperator {
            get {
                return this.LogicalOperatorField;
            }
            set {
                if ((this.LogicalOperatorField.Equals(value) != true)) {
                    this.LogicalOperatorField = value;
                    this.RaisePropertyChanged("LogicalOperator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.ReturnListType ListReturnTypes {
            get {
                return this.ListReturnTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.ListReturnTypesField, value) != true)) {
                    this.ListReturnTypesField = value;
                    this.RaisePropertyChanged("ListReturnTypes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.SortFields SortFields {
            get {
                return this.SortFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.SortFieldsField, value) != true)) {
                    this.SortFieldsField = value;
                    this.RaisePropertyChanged("SortFields");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnListType", Namespace="http://asa.org/contracts/apptoolServiceCriteria")]
    [System.SerializableAttribute()]
    public partial class ReturnListType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASA.Web.Services.AppToolService.Proxy.AppTool.YNFlagType AppToolTier2TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASA.Web.Services.AppToolService.Proxy.AppTool.YNFlagType AppToolInfoTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASA.Web.Services.AppToolService.Proxy.AppTool.YNFlagType AppToolTier3TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.YNFlagType AppToolTier2Type {
            get {
                return this.AppToolTier2TypeField;
            }
            set {
                if ((this.AppToolTier2TypeField.Equals(value) != true)) {
                    this.AppToolTier2TypeField = value;
                    this.RaisePropertyChanged("AppToolTier2Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.YNFlagType AppToolInfoType {
            get {
                return this.AppToolInfoTypeField;
            }
            set {
                if ((this.AppToolInfoTypeField.Equals(value) != true)) {
                    this.AppToolInfoTypeField = value;
                    this.RaisePropertyChanged("AppToolInfoType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.YNFlagType AppToolTier3Type {
            get {
                return this.AppToolTier3TypeField;
            }
            set {
                if ((this.AppToolTier3TypeField.Equals(value) != true)) {
                    this.AppToolTier3TypeField = value;
                    this.RaisePropertyChanged("AppToolTier3Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortFields", Namespace="http://asa.org/contracts/apptoolServiceCriteria")]
    [System.SerializableAttribute()]
    public partial class SortFields : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<ASA.Web.Services.AppToolService.Proxy.AppTool.SortOperatorType> ToolTypeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<ASA.Web.Services.AppToolService.Proxy.AppTool.SortOperatorType> ToolTypeId {
            get {
                return this.ToolTypeIdField;
            }
            set {
                if ((this.ToolTypeIdField.Equals(value) != true)) {
                    this.ToolTypeIdField = value;
                    this.RaisePropertyChanged("ToolTypeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CriteriaAppTool_PersonAppToolType", Namespace="http://asa.org/contracts/apptoolServiceCriteria")]
    [System.SerializableAttribute()]
    public partial class CriteriaAppTool_PersonAppToolType : ASA.Web.Services.AppToolService.Proxy.AppTool.AppToolServiceCriteriaType {
        
        private ASA.Web.Services.AppToolService.Proxy.AppTool.CriterionPersonIdType CriterionPersonIdField;
        
        private ASA.Web.Services.AppToolService.Proxy.AppTool.CriterionCustomerIdType CriterionCustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASA.Web.Services.AppToolService.Proxy.AppTool.CriterionAppToolTypeIdType CriterionAppToolTypeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.CriterionPersonIdType CriterionPersonId {
            get {
                return this.CriterionPersonIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CriterionPersonIdField, value) != true)) {
                    this.CriterionPersonIdField = value;
                    this.RaisePropertyChanged("CriterionPersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.CriterionCustomerIdType CriterionCustomerId {
            get {
                return this.CriterionCustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CriterionCustomerIdField, value) != true)) {
                    this.CriterionCustomerIdField = value;
                    this.RaisePropertyChanged("CriterionCustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.CriterionAppToolTypeIdType CriterionAppToolTypeId {
            get {
                return this.CriterionAppToolTypeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CriterionAppToolTypeIdField, value) != true)) {
                    this.CriterionAppToolTypeIdField = value;
                    this.RaisePropertyChanged("CriterionAppToolTypeId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogicalOperatorType", Namespace="http://asa.org/contracts/apptoolServiceCriteria")]
    public enum LogicalOperatorType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AND = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OR = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YNFlagType", Namespace="http://asa.org/contracts/commonTypes")]
    public enum YNFlagType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        U = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Y = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        N = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SortOperatorType", Namespace="http://asa.org/contracts/apptoolServiceCriteria")]
    public enum SortOperatorType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ASC = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DESC = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CriterionPersonIdType", Namespace="http://asa.org/contracts/apptoolServiceCriteria")]
    [System.SerializableAttribute()]
    public partial class CriterionPersonIdType : ASA.Web.Services.AppToolService.Proxy.AppTool.CriterionType {
        
        private int PersonIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CriterionCustomerIdType", Namespace="http://asa.org/contracts/apptoolServiceCriteria")]
    [System.SerializableAttribute()]
    public partial class CriterionCustomerIdType : ASA.Web.Services.AppToolService.Proxy.AppTool.CriterionType {
        
        private int CustomerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CriterionAppToolTypeIdType", Namespace="http://asa.org/contracts/apptoolServiceCriteria")]
    [System.SerializableAttribute()]
    public partial class CriterionAppToolTypeIdType : ASA.Web.Services.AppToolService.Proxy.AppTool.CriterionType {
        
        private ASA.Web.Services.AppToolService.Proxy.AppTool.ApplicationToolType ToolTypeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.ApplicationToolType ToolTypeId {
            get {
                return this.ToolTypeIdField;
            }
            set {
                if ((this.ToolTypeIdField.Equals(value) != true)) {
                    this.ToolTypeIdField = value;
                    this.RaisePropertyChanged("ToolTypeId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CriterionType", Namespace="http://asa.org/contracts/apptoolServiceCriteria")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ASA.Web.Services.AppToolService.Proxy.AppTool.CriterionCustomerIdType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ASA.Web.Services.AppToolService.Proxy.AppTool.CriterionAppToolTypeIdType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ASA.Web.Services.AppToolService.Proxy.AppTool.CriterionPersonIdType))]
    public partial class CriterionType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ASA.Web.Services.AppToolService.Proxy.AppTool.RelationalOperatorType RelationalOperatorField;
        
        private ASA.Web.Services.AppToolService.Proxy.AppTool.LogicalOperatorType LogicalOperatorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.RelationalOperatorType RelationalOperator {
            get {
                return this.RelationalOperatorField;
            }
            set {
                if ((this.RelationalOperatorField.Equals(value) != true)) {
                    this.RelationalOperatorField = value;
                    this.RaisePropertyChanged("RelationalOperator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.LogicalOperatorType LogicalOperator {
            get {
                return this.LogicalOperatorField;
            }
            set {
                if ((this.LogicalOperatorField.Equals(value) != true)) {
                    this.LogicalOperatorField = value;
                    this.RaisePropertyChanged("LogicalOperator");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelationalOperatorType", Namespace="http://asa.org/contracts/apptoolServiceCriteria")]
    public enum RelationalOperatorType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EQUALS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STARTSWITH = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ENDSWITH = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationToolType", Namespace="http://asa.org/contracts/apptool")]
    public enum ApplicationToolType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SRC = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GRC = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IRC = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DFC = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FBC = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppToolCanonicalType", Namespace="http://asa.org/contracts/apptool")]
    [System.SerializableAttribute()]
    public partial class AppToolCanonicalType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ASA.Web.Services.AppToolService.Proxy.AppTool.AppToolTier1Type AppToolTier1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASA.Web.Services.AppToolService.Proxy.AppTool.AppToolTier2Type AppToolTier2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASA.Web.Services.AppToolService.Proxy.AppTool.AppToolTier3Type AppToolTier3Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.AppToolTier1Type AppToolTier1 {
            get {
                return this.AppToolTier1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AppToolTier1Field, value) != true)) {
                    this.AppToolTier1Field = value;
                    this.RaisePropertyChanged("AppToolTier1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.AppToolTier2Type AppToolTier2 {
            get {
                return this.AppToolTier2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AppToolTier2Field, value) != true)) {
                    this.AppToolTier2Field = value;
                    this.RaisePropertyChanged("AppToolTier2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.AppToolTier3Type AppToolTier3 {
            get {
                return this.AppToolTier3Field;
            }
            set {
                if ((object.ReferenceEquals(this.AppToolTier3Field, value) != true)) {
                    this.AppToolTier3Field = value;
                    this.RaisePropertyChanged("AppToolTier3");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppToolTier1Type", Namespace="http://asa.org/contracts/apptool")]
    [System.SerializableAttribute()]
    public partial class AppToolTier1Type : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PersonIdField;
        
        private int CustomerIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PersonId {
            get {
                return this.PersonIdField;
            }
            set {
                if ((this.PersonIdField.Equals(value) != true)) {
                    this.PersonIdField = value;
                    this.RaisePropertyChanged("PersonId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppToolTier2Type", Namespace="http://asa.org/contracts/apptool")]
    [System.SerializableAttribute()]
    public partial class AppToolTier2Type : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ASA.Web.Services.AppToolService.Proxy.AppTool.AppToolTier2Type.AppToolInfoTypeType AppToolInfoTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.AppToolTier2Type.AppToolInfoTypeType AppToolInfoType {
            get {
                return this.AppToolInfoTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AppToolInfoTypeField, value) != true)) {
                    this.AppToolInfoTypeField = value;
                    this.RaisePropertyChanged("AppToolInfoType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="AppToolTier2Type.AppToolInfoTypeType", Namespace="http://asa.org/contracts/apptool")]
        [System.SerializableAttribute()]
        public partial class AppToolInfoTypeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int AppToolPersonIdField;
            
            private ASA.Web.Services.AppToolService.Proxy.AppTool.ApplicationToolType AppToolTypeField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private decimal PrincipalAmountField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private double InterestRateField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int NumberOfPaymentsField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private decimal MonthlyIncomeField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int NumberOfMonthsInForbearanceField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private decimal ForbearancePaymentAmountField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int NumberOfForbearancePaymentsField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private decimal BalanceAtStartDefermentField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private int NumberOfMonthsInDefermentField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private byte[] RecordVersionField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int AppToolPersonId {
                get {
                    return this.AppToolPersonIdField;
                }
                set {
                    if ((this.AppToolPersonIdField.Equals(value) != true)) {
                        this.AppToolPersonIdField = value;
                        this.RaisePropertyChanged("AppToolPersonId");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
            public ASA.Web.Services.AppToolService.Proxy.AppTool.ApplicationToolType AppToolType {
                get {
                    return this.AppToolTypeField;
                }
                set {
                    if ((this.AppToolTypeField.Equals(value) != true)) {
                        this.AppToolTypeField = value;
                        this.RaisePropertyChanged("AppToolType");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public decimal PrincipalAmount {
                get {
                    return this.PrincipalAmountField;
                }
                set {
                    if ((this.PrincipalAmountField.Equals(value) != true)) {
                        this.PrincipalAmountField = value;
                        this.RaisePropertyChanged("PrincipalAmount");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
            public double InterestRate {
                get {
                    return this.InterestRateField;
                }
                set {
                    if ((this.InterestRateField.Equals(value) != true)) {
                        this.InterestRateField = value;
                        this.RaisePropertyChanged("InterestRate");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
            public int NumberOfPayments {
                get {
                    return this.NumberOfPaymentsField;
                }
                set {
                    if ((this.NumberOfPaymentsField.Equals(value) != true)) {
                        this.NumberOfPaymentsField = value;
                        this.RaisePropertyChanged("NumberOfPayments");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
            public decimal MonthlyIncome {
                get {
                    return this.MonthlyIncomeField;
                }
                set {
                    if ((this.MonthlyIncomeField.Equals(value) != true)) {
                        this.MonthlyIncomeField = value;
                        this.RaisePropertyChanged("MonthlyIncome");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
            public int NumberOfMonthsInForbearance {
                get {
                    return this.NumberOfMonthsInForbearanceField;
                }
                set {
                    if ((this.NumberOfMonthsInForbearanceField.Equals(value) != true)) {
                        this.NumberOfMonthsInForbearanceField = value;
                        this.RaisePropertyChanged("NumberOfMonthsInForbearance");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
            public decimal ForbearancePaymentAmount {
                get {
                    return this.ForbearancePaymentAmountField;
                }
                set {
                    if ((this.ForbearancePaymentAmountField.Equals(value) != true)) {
                        this.ForbearancePaymentAmountField = value;
                        this.RaisePropertyChanged("ForbearancePaymentAmount");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
            public int NumberOfForbearancePayments {
                get {
                    return this.NumberOfForbearancePaymentsField;
                }
                set {
                    if ((this.NumberOfForbearancePaymentsField.Equals(value) != true)) {
                        this.NumberOfForbearancePaymentsField = value;
                        this.RaisePropertyChanged("NumberOfForbearancePayments");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
            public decimal BalanceAtStartDeferment {
                get {
                    return this.BalanceAtStartDefermentField;
                }
                set {
                    if ((this.BalanceAtStartDefermentField.Equals(value) != true)) {
                        this.BalanceAtStartDefermentField = value;
                        this.RaisePropertyChanged("BalanceAtStartDeferment");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
            public int NumberOfMonthsInDeferment {
                get {
                    return this.NumberOfMonthsInDefermentField;
                }
                set {
                    if ((this.NumberOfMonthsInDefermentField.Equals(value) != true)) {
                        this.NumberOfMonthsInDefermentField = value;
                        this.RaisePropertyChanged("NumberOfMonthsInDeferment");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
            public byte[] RecordVersion {
                get {
                    return this.RecordVersionField;
                }
                set {
                    if ((object.ReferenceEquals(this.RecordVersionField, value) != true)) {
                        this.RecordVersionField = value;
                        this.RaisePropertyChanged("RecordVersion");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppToolTier3Type", Namespace="http://asa.org/contracts/apptool")]
    [System.SerializableAttribute()]
    public partial class AppToolTier3Type : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ResponseMessageList", Namespace="http://amsa.com/contract/ASA.Common.ResponseMessage/v1.0", ItemName="ResponseMessage")]
    [System.SerializableAttribute()]
    public class ResponseMessageList : System.Collections.Generic.List<ASA.Web.Services.AppToolService.Proxy.AppTool.ResponseMessage> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessage", Namespace="http://amsa.com/contract/ASA.Common.ResponseMessage/v1.0")]
    [System.SerializableAttribute()]
    public partial class ResponseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetEntityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetEntityPrimaryKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageDetails {
            get {
                return this.MessageDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageDetailsField, value) != true)) {
                    this.MessageDetailsField = value;
                    this.RaisePropertyChanged("MessageDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetEntityName {
            get {
                return this.TargetEntityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetEntityNameField, value) != true)) {
                    this.TargetEntityNameField = value;
                    this.RaisePropertyChanged("TargetEntityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetEntityPrimaryKey {
            get {
                return this.TargetEntityPrimaryKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetEntityPrimaryKeyField, value) != true)) {
                    this.TargetEntityPrimaryKeyField = value;
                    this.RaisePropertyChanged("TargetEntityPrimaryKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://asa.org/servicecontract/apptool/v1.0", ConfigurationName="AppTool.IAppTool")]
    public interface IAppTool {
        
        // CODEGEN: Generating message contract since the wrapper name (GetAppToolRequest) of message GetAppToolRequest does not match the default value (GetAppTool)
        [System.ServiceModel.OperationContractAttribute(Action="GetAppTool", ReplyAction="http://asa.org/servicecontract/apptool/v1.0/IAppTool/GetAppToolResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ASA.ErrorHandling.ASABusinessFaultDetail), Action="ASABusinessFaultDetail", Name="ASABusinessFaultDetail", Namespace="http://amsa.com/contract/errorHandling/v1.0")]
        [System.ServiceModel.FaultContractAttribute(typeof(ASA.ErrorHandling.ASAFaultDetail), Action="ASAFaultDetail", Name="ASAFaultDetail", Namespace="http://amsa.com/contract/errorHandling/v1.0")]
        ASA.Web.Services.AppToolService.Proxy.AppTool.GetAppToolResponse GetAppTool(ASA.Web.Services.AppToolService.Proxy.AppTool.GetAppToolRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (SaveAppToolRequest) of message SaveAppToolRequest does not match the default value (SaveAppTool)
        [System.ServiceModel.OperationContractAttribute(Action="SaveAppTool", ReplyAction="http://asa.org/servicecontract/apptool/v1.0/IAppTool/SaveAppToolResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ASA.ErrorHandling.ASAFaultDetail), Action="ASAFaultDetail", Name="ASAFaultDetail", Namespace="http://amsa.com/contract/errorHandling/v1.0")]
        [System.ServiceModel.FaultContractAttribute(typeof(ASA.ErrorHandling.ASABusinessFaultDetail), Action="ASABusinessFaultDetail", Name="ASABusinessFaultDetail", Namespace="http://amsa.com/contract/errorHandling/v1.0")]
        ASA.Web.Services.AppToolService.Proxy.AppTool.SaveAppToolResponse SaveAppTool(ASA.Web.Services.AppToolService.Proxy.AppTool.SaveAppToolRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAppToolRequest", WrapperNamespace="http://asa.org/servicecontract/apptool/v1.0", IsWrapped=true)]
    public partial class GetAppToolRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://amsa.com/contract/baserequestcontract/v1.0")]
        public System.Collections.Generic.Dictionary<string, string> ParamList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asa.org/servicecontract/apptool/v1.0", Order=0)]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.AppToolServiceCriteriaType Criteria;
        
        public GetAppToolRequest() {
        }
        
        public GetAppToolRequest(System.Collections.Generic.Dictionary<string, string> ParamList, ASA.Web.Services.AppToolService.Proxy.AppTool.AppToolServiceCriteriaType Criteria) {
            this.ParamList = ParamList;
            this.Criteria = Criteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAppToolResponse", WrapperNamespace="http://asa.org/servicecontract/apptool/v1.0", IsWrapped=true)]
    public partial class GetAppToolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asa.org/servicecontract/apptool/v1.0", Order=0)]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.AppToolCanonicalType[] AppToolCanonicalList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asa.org/servicecontract/apptool/v1.0", Order=1)]
        public int ResultCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asa.org/servicecontract/apptool/v1.0", Order=2)]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.ResponseMessageList ResponseMessageList;
        
        public GetAppToolResponse() {
        }
        
        public GetAppToolResponse(ASA.Web.Services.AppToolService.Proxy.AppTool.AppToolCanonicalType[] AppToolCanonicalList, int ResultCode, ASA.Web.Services.AppToolService.Proxy.AppTool.ResponseMessageList ResponseMessageList) {
            this.AppToolCanonicalList = AppToolCanonicalList;
            this.ResultCode = ResultCode;
            this.ResponseMessageList = ResponseMessageList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveAppToolRequest", WrapperNamespace="http://asa.org/servicecontract/apptool/v1.0", IsWrapped=true)]
    public partial class SaveAppToolRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://amsa.com/contract/baserequestcontract/v1.0")]
        public System.Collections.Generic.Dictionary<string, string> ParamList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asa.org/servicecontract/apptool/v1.0", Order=0)]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.AppToolCanonicalType AppToolCanonical;
        
        public SaveAppToolRequest() {
        }
        
        public SaveAppToolRequest(System.Collections.Generic.Dictionary<string, string> ParamList, ASA.Web.Services.AppToolService.Proxy.AppTool.AppToolCanonicalType AppToolCanonical) {
            this.ParamList = ParamList;
            this.AppToolCanonical = AppToolCanonical;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveAppToolResponse", WrapperNamespace="http://asa.org/servicecontract/apptool/v1.0", IsWrapped=true)]
    public partial class SaveAppToolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asa.org/servicecontract/apptool/v1.0", Order=0)]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.AppToolCanonicalType AppToolCanonical;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asa.org/servicecontract/apptool/v1.0", Order=1)]
        public int ResultCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://asa.org/servicecontract/apptool/v1.0", Order=2)]
        public ASA.Web.Services.AppToolService.Proxy.AppTool.ResponseMessageList ResponseMessageList;
        
        public SaveAppToolResponse() {
        }
        
        public SaveAppToolResponse(ASA.Web.Services.AppToolService.Proxy.AppTool.AppToolCanonicalType AppToolCanonical, int ResultCode, ASA.Web.Services.AppToolService.Proxy.AppTool.ResponseMessageList ResponseMessageList) {
            this.AppToolCanonical = AppToolCanonical;
            this.ResultCode = ResultCode;
            this.ResponseMessageList = ResponseMessageList;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAppToolChannel : ASA.Web.Services.AppToolService.Proxy.AppTool.IAppTool, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppToolClient : System.ServiceModel.ClientBase<ASA.Web.Services.AppToolService.Proxy.AppTool.IAppTool>, ASA.Web.Services.AppToolService.Proxy.AppTool.IAppTool {
        
        public AppToolClient() {
        }
        
        public AppToolClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AppToolClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppToolClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppToolClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASA.Web.Services.AppToolService.Proxy.AppTool.GetAppToolResponse ASA.Web.Services.AppToolService.Proxy.AppTool.IAppTool.GetAppTool(ASA.Web.Services.AppToolService.Proxy.AppTool.GetAppToolRequest request) {
            return base.Channel.GetAppTool(request);
        }
        
        public ASA.Web.Services.AppToolService.Proxy.AppTool.AppToolCanonicalType[] GetAppTool(System.Collections.Generic.Dictionary<string, string> ParamList, ASA.Web.Services.AppToolService.Proxy.AppTool.AppToolServiceCriteriaType Criteria, out int ResultCode, out ASA.Web.Services.AppToolService.Proxy.AppTool.ResponseMessageList ResponseMessageList) {
            ASA.Web.Services.AppToolService.Proxy.AppTool.GetAppToolRequest inValue = new ASA.Web.Services.AppToolService.Proxy.AppTool.GetAppToolRequest();
            inValue.ParamList = ParamList;
            inValue.Criteria = Criteria;
            ASA.Web.Services.AppToolService.Proxy.AppTool.GetAppToolResponse retVal = ((ASA.Web.Services.AppToolService.Proxy.AppTool.IAppTool)(this)).GetAppTool(inValue);
            ResultCode = retVal.ResultCode;
            ResponseMessageList = retVal.ResponseMessageList;
            return retVal.AppToolCanonicalList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASA.Web.Services.AppToolService.Proxy.AppTool.SaveAppToolResponse ASA.Web.Services.AppToolService.Proxy.AppTool.IAppTool.SaveAppTool(ASA.Web.Services.AppToolService.Proxy.AppTool.SaveAppToolRequest request) {
            return base.Channel.SaveAppTool(request);
        }
        
        public int SaveAppTool(System.Collections.Generic.Dictionary<string, string> ParamList, ref ASA.Web.Services.AppToolService.Proxy.AppTool.AppToolCanonicalType AppToolCanonical, out ASA.Web.Services.AppToolService.Proxy.AppTool.ResponseMessageList ResponseMessageList) {
            ASA.Web.Services.AppToolService.Proxy.AppTool.SaveAppToolRequest inValue = new ASA.Web.Services.AppToolService.Proxy.AppTool.SaveAppToolRequest();
            inValue.ParamList = ParamList;
            inValue.AppToolCanonical = AppToolCanonical;
            ASA.Web.Services.AppToolService.Proxy.AppTool.SaveAppToolResponse retVal = ((ASA.Web.Services.AppToolService.Proxy.AppTool.IAppTool)(this)).SaveAppTool(inValue);
            AppToolCanonical = retVal.AppToolCanonical;
            ResponseMessageList = retVal.ResponseMessageList;
            return retVal.ResultCode;
        }
    }
}
